const doctors=[
{name:'Dr. Ananya Sharma',spec:'General Physician',exp:'12 yrs',rating:'4.9',icon:'👩‍⚕️',fee:499,languages:'Hindi, English',about:'General medicine, fever, infections, diabetes and routine health concerns.',symptoms:'fever cough diabetes weakness',today:true,tomorrow:true,times:['10:00 AM','11:30 AM','4:30 PM']},
{name:'Dr. Rahul Verma',spec:'Cardiologist',exp:'15 yrs',rating:'4.8',icon:'👨‍⚕️',fee:799,languages:'Hindi, English',about:'Heart health, blood pressure, cholesterol and cardiac follow-up consultations.',symptoms:'chest blood pressure heart hypertension',today:true,tomorrow:true,times:['9:30 AM','1:00 PM','6:00 PM']},
{name:'Dr. Neha Singh',spec:'Dermatologist',exp:'9 yrs',rating:'4.9',icon:'👩‍⚕️',fee:599,languages:'Hindi, English',about:'Skin, hair and common dermatology concerns with remote consultation.',symptoms:'skin acne hair allergy rash',today:false,tomorrow:true,times:['11:00 AM','2:30 PM','7:00 PM']},
{name:'Dr. Arjun Mehta',spec:'Pediatrician',exp:'11 yrs',rating:'4.8',icon:'👨‍⚕️',fee:549,languages:'Hindi, English',about:'Child health, growth, nutrition, fever and common pediatric concerns.',symptoms:'child baby fever cough nutrition',today:true,tomorrow:true,times:['10:30 AM','3:00 PM','5:30 PM']},
{name:'Dr. Priya Nair',spec:'Gynecologist',exp:'13 yrs',rating:'4.9',icon:'👩‍⚕️',fee:699,languages:'English, Hindi',about:'Women’s health, menstrual concerns, prenatal counselling and follow-ups.',symptoms:'women pregnancy period pcos',today:true,tomorrow:false,times:['10:00 AM','12:30 PM','5:00 PM']},
{name:'Dr. Vivek Rao',spec:'General Physician',exp:'8 yrs',rating:'4.7',icon:'👨‍⚕️',fee:399,languages:'Hindi, English',about:'Primary care, seasonal illnesses and general health consultations.',symptoms:'cold fever cough weakness',today:true,tomorrow:true,times:['9:00 AM','1:30 PM','6:30 PM']},
{name:'Dr. Meera Joshi',spec:'Dermatologist',exp:'10 yrs',rating:'4.8',icon:'👩‍⚕️',fee:599,languages:'Hindi, English',about:'Clinical dermatology, acne, pigmentation and hair-related concerns.',symptoms:'skin acne pigmentation hair',today:false,tomorrow:true,times:['10:30 AM','3:30 PM','6:30 PM']},
{name:'Dr. Karan Gupta',spec:'Cardiologist',exp:'17 yrs',rating:'4.9',icon:'👨‍⚕️',fee:899,languages:'Hindi, English',about:'Cardiology consultation and long-term heart-health management.',symptoms:'heart chest blood pressure cholesterol',today:true,tomorrow:true,times:['8:30 AM','12:00 PM','7:30 PM']},
{name:'Dr. Rohan Das',spec:'Orthopedic',exp:'14 yrs',rating:'4.8',icon:'👨‍⚕️',fee:699,languages:'Hindi, English',about:'Bone, joint, back and sports-injury consultations.',symptoms:'bone joint back knee pain fracture',today:true,tomorrow:true,times:['11:00 AM','2:00 PM','5:00 PM']},
{name:'Dr. Kavya Menon',spec:'ENT',exp:'10 yrs',rating:'4.8',icon:'👩‍⚕️',fee:549,languages:'English, Hindi',about:'Ear, nose and throat consultations for common ENT concerns.',symptoms:'ear nose throat sinus allergy',today:true,tomorrow:true,times:['9:30 AM','1:30 PM','4:00 PM']}];
let appointments=JSON.parse(localStorage.getItem('ss_appts')||'[]');let selectedDoctor=doctors[0],selectedDate=null,selectedTime=null;
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'});}
function getAccount(){try{return JSON.parse(localStorage.getItem('ss_account')||'null')}catch{return null}}
function updatePatient(){const a=getAccount();const name=a?.name||'Patient';document.querySelectorAll('#headerPatientName,#dashName').forEach(e=>e.textContent=name);const av=document.getElementById('profileAvatar');if(av)av.textContent=name.charAt(0).toUpperCase();const pn=document.getElementById('profileName');if(pn)pn.textContent=name;}
function renderDoctors(){const q=(document.getElementById('doctorSearch')?.value||'').trim().toLowerCase();const f=document.getElementById('speciality')?.value||'all';const av=document.getElementById('availabilityFilter')?.value||'all';const list=doctors.filter(d=>(f==='all'||d.spec===f)&&(!q||`${d.name} ${d.spec} ${d.symptoms}`.toLowerCase().includes(q))&&(av==='all'||(av==='today'?d.today:d.tomorrow)));const grid=document.getElementById('doctorGrid');grid.innerHTML=list.map(d=>`<article class="doctor"><div class="avatar">${d.icon}</div><h3>${d.name}</h3><p>${d.spec} · ${d.exp} experience</p><div class="rating">⭐ ${d.rating} <span class="muted">· Verified</span></div><div class="tags"><span class="tag">₹${d.fee}</span><span class="tag">${d.today?'Today':'Tomorrow'}</span></div><button class="secondary full" onclick="viewDoctor('${d.name}')">View profile</button><button class="primary full" onclick="openBooking('${d.name}')">Book now</button></article>`).join('');document.getElementById('noDoctors').hidden=list.length>0;}
function viewDoctor(name){selectedDoctor=doctors.find(d=>d.name===name)||doctors[0];document.getElementById('doctorDetail').innerHTML=`<div class="detail-avatar">${selectedDoctor.icon}</div><span class="eyebrow">✓ VERIFIED DOCTOR</span><h3>${selectedDoctor.name}</h3><p class="muted">${selectedDoctor.spec} · ${selectedDoctor.exp} experience</p><p>${selectedDoctor.about}</p><div class="detail-grid"><div class="detail-box"><small>Rating</small><b>⭐ ${selectedDoctor.rating}/5</b></div><div class="detail-box"><small>Consultation fee</small><b>₹${selectedDoctor.fee}</b></div><div class="detail-box"><small>Languages</small><b>${selectedDoctor.languages}</b></div><div class="detail-box"><small>Availability</small><b>${selectedDoctor.today?'Today':'Tomorrow'}</b></div></div><div class="tags"><span class="tag">Video</span><span class="tag">Audio</span><span class="tag">Chat</span></div>`;document.getElementById('doctorBookBtn').onclick=()=>{closeDoctor();openBooking(selectedDoctor.name)};show('doctorModal');}
function openBooking(name){if(name)selectedDoctor=doctors.find(d=>d.name===name)||doctors[0];const sel=document.getElementById('doctorSelect');sel.innerHTML=doctors.map(d=>`<option value="${d.name}" ${d.name===selectedDoctor.name?'selected':''}>${d.name} — ${d.spec}</option>`).join('');sel.onchange=()=>{selectedDoctor=doctors.find(d=>d.name===sel.value)||doctors[0];buildDates();};selectedDate=null;selectedTime=null;buildDates();show('bookingModal');}
function buildDates(){const wrap=document.getElementById('dateCards');const days=[];for(let i=0;i<7;i++){const dt=new Date();dt.setHours(0,0,0,0);dt.setDate(dt.getDate()+i);days.push(dt)}wrap.innerHTML=days.map((dt,i)=>{const ok=i===0?selectedDoctor.today:selectedDoctor.tomorrow;const value=dt.toISOString().slice(0,10);return `<button class="date-card ${(!selectedDate&&i===0&&ok)?'selected':''} ${!ok?'disabled':''}" ${ok?'onclick="selectDate(\''+value+'\')"':''}><small>${i===0?'Today':i===1?'Tomorrow':dt.toLocaleDateString('en',{weekday:'short'})}</small><b>${dt.getDate()}</b><small>${dt.toLocaleDateString('en',{month:'short'})}</small></button>`}).join('');if(!selectedDate){const first=days.find((_,i)=>i===0?selectedDoctor.today:selectedDoctor.tomorrow);selectedDate=first?first.toISOString().slice(0,10):days[1].toISOString().slice(0,10)}renderDateSelection();}
function selectDate(value){selectedDate=value;selectedTime=null;renderDateSelection();}
function renderDateSelection(){document.querySelectorAll('.date-card').forEach((el)=>{const txt=el.getAttribute('onclick')||'';el.classList.toggle('selected',selectedDate&&txt.includes(selectedDate))});document.getElementById('timeSlots').innerHTML=selectedDoctor.times.map(t=>`<button class="time-slot ${t===selectedTime?'selected':''}" onclick="selectTime('${t}')">${t}</button>`).join('');document.getElementById('feeBox').innerHTML=`<span>Consultation fee</span><b>₹${selectedDoctor.fee}</b>`;}
function selectTime(t){selectedTime=t;renderDateSelection();}
function confirmBooking(){if(!selectedDate||!selectedTime){toast('Please choose a date and time');return}const mode=document.getElementById('mode').value;const id='SS-'+Date.now().toString().slice(-8);const a={id,doctor:selectedDoctor.name,spec:selectedDoctor.spec,date:selectedDate,time:selectedTime,mode,fee:selectedDoctor.fee,status:'Confirmed'};appointments.push(a);localStorage.setItem('ss_appts',JSON.stringify(appointments));closeBooking();renderAppointments();document.getElementById('confirmationDetail').innerHTML=`<p><b>${selectedDoctor.name}</b></p><p>${selectedDoctor.spec}</p><p>📅 ${formatDate(selectedDate)} · ⏰ ${selectedTime}</p><p>📹 ${mode} · ₹${selectedDoctor.fee}</p><p class="id">Appointment ID: ${id}</p>`;show('confirmationModal');updateDashboard();}
function renderAppointments(){const el=document.getElementById('appointmentsList');if(!appointments.length){el.innerHTML='<div class="appt"><div class="datebox">📅</div><div><b>No upcoming appointments</b><small>Choose a specialist to book your first consultation.</small></div><button onclick="openBooking()">Book now</button></div>';return}el.innerHTML=appointments.slice().reverse().map(a=>`<div class="appt"><div class="datebox"><b>${new Date(a.date+'T00:00:00').getDate()}</b><small>${new Date(a.date+'T00:00:00').toLocaleDateString('en',{month:'short'})}</small></div><div><b>${a.doctor}</b><small>${formatDate(a.date)} · ${a.time} · ${a.mode}</small><small class="id">${a.id||''}</small></div><button onclick="toast('Consultation room demo — connect video provider for production')">Join</button></div>`).join('');}
function updateDashboard(){document.getElementById('dashAppointments').textContent=appointments.length}
function formatDate(s){return new Date(s+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}
function show(id){document.getElementById(id).classList.add('show');document.getElementById(id).setAttribute('aria-hidden','false')}
function hide(id){document.getElementById(id).classList.remove('show');document.getElementById(id).setAttribute('aria-hidden','true')}
function closeDoctor(){hide('doctorModal')}function closeBooking(){hide('bookingModal')}function closeConfirmation(){hide('confirmationModal')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2600)}
updatePatient();renderDoctors();renderAppointments();updateDashboard();
